jobs:
- job: linux_64
  pool:
    vmImage: ubuntu-16.04
  timeoutInMinutes: 240
  strategy:
    maxParallel: 8
    matrix:
      linux_c_compilergcccgo1cgo_varcgocxx_compilergxxfortran_compilergfortrantarget_platformlinux-64:
        CONFIG: linux_c_compilergcccgo1cgo_varcgocxx_compilergxxfortran_compilergfortrantarget_platformlinux-64
      linux_c_compilertoolchain_ccgo1cgo_varcgocxx_compilertoolchain_cxxfortran_compilertoolchain_forttarget_platformlinux-64:
        CONFIG: linux_c_compilertoolchain_ccgo1cgo_varcgocxx_compilertoolchain_cxxfortran_compilertoolchain_forttarget_platformlinux-64
  steps:
  - script: |
      sudo pip install --upgrade pip
      sudo pip install setuptools shyaml
    displayName: Install dependencies

  - script: .azure-pipelines/run_docker_build.sh
    displayName: Run docker build